apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp_container
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp_container
  template:
    metadata:
      labels:
        app: myapp_container
    spec:
      containers:
        - name: myapp_container
          image: devops:latest
